import { mkdir, writeFile } from 'fs/promises'
import { join } from 'path'
import type { DetectedStack, DesignToken, ComponentPattern } from '@vibe-design/detector'

export { generateSkills, generateVibeConfig, generateClaudeSkill }

async function generateSkills(
  projectDir: string,
  stack: DetectedStack
): Promise<void> {
  const skillsDir = join(projectDir, '.vibe', 'skills')
  await mkdir(skillsDir, { recursive: true })

  const generators: Array<[string, string]> = [
    ['CONVENTIONS.md', generateConventions(stack)],
  ]

  if (stack.css === 'tailwind') {
    generators.push(['TAILWIND.md', generateTailwindSkill(stack)])
  }

  if (stack.componentPatterns.length > 0) {
    generators.push(['COMPONENTS.md', generateComponentsSkill(stack)])
  }

  await Promise.all(
    generators.map(([name, content]) => writeFile(join(skillsDir, name), content))
  )
}

function generateTailwindSkill(stack: DetectedStack): string {
  const lines: string[] = [
    '# Tailwind Design System',
    '<!-- Auto-generated by vibe-design sync — do not edit manually -->',
    '',
  ]

  const configFile = stack.typescript ? 'tailwind.config.ts' : 'tailwind.config.js'
  lines.push(`Config: \`${configFile}\` · Version: ${stack.tailwindVersion || 'unknown'}`)
  lines.push('')

  // Custom colors
  const colorTokens = stack.designTokens.filter(t => t.category === 'color' && !t.name.startsWith('--'))
  if (colorTokens.length > 0) {
    lines.push('## Custom Colors')
    for (const token of colorTokens) {
      const ref = token.nearestDefault ? `  (${token.nearestDefault})` : ''
      lines.push(`- \`${token.name}\`: ${token.value}${ref}`)
    }
    lines.push('')
  }

  // CSS custom properties
  const cssVars = stack.designTokens.filter(t => t.name.startsWith('--'))
  if (cssVars.length > 0) {
    lines.push('## CSS Custom Properties')
    for (const token of cssVars) {
      lines.push(`- \`${token.name}\`: ${token.value}`)
    }
    lines.push('')
  }

  // Typography patterns (from scanning)
  lines.push('## Typography Patterns')
  lines.push('_(Scan your codebase for common text-* patterns to populate this section)_')
  lines.push('')

  // Spacing patterns
  const spacingTokens = stack.designTokens.filter(t => t.category === 'spacing')
  if (spacingTokens.length > 0) {
    lines.push('## Custom Spacing')
    for (const token of spacingTokens) {
      lines.push(`- \`${token.name}\`: ${token.value}`)
    }
    lines.push('')
  }

  // Border radius
  const radiusTokens = stack.designTokens.filter(t => t.category === 'borderRadius')
  if (radiusTokens.length > 0) {
    lines.push('## Custom Border Radius')
    for (const token of radiusTokens) {
      lines.push(`- \`${token.name}\`: ${token.value}`)
    }
    lines.push('')
  }

  lines.push('## Rules')
  lines.push('- Never use arbitrary values like w-[437px] — use nearest scale value')
  lines.push('- Border radius: rounded-md default, rounded-lg for cards, rounded-full for pills')
  lines.push('- Shadows: shadow-sm (subtle), shadow-md (card), shadow-lg (modal/overlay)')
  lines.push('- Prefer semantic color tokens over raw Tailwind colors when available')
  lines.push('')

  return lines.join('\n')
}

function generateComponentsSkill(stack: DetectedStack): string {
  const lines: string[] = [
    '# Component Conventions',
    '<!-- Auto-generated by vibe-design sync -->',
    '',
  ]

  // Component library info
  if (stack.components !== 'custom') {
    lines.push(`## Library: ${stack.components}`)
    lines.push(`Components live in: \`${stack.componentsDir}ui/\``)
  } else {
    lines.push('## Custom Components')
    lines.push(`Components live in: \`${stack.componentsDir}\``)
  }

  // Detect dominant styling pattern
  const patternCounts = new Map<string, number>()
  for (const comp of stack.componentPatterns) {
    const count = patternCounts.get(comp.stylingPattern) ?? 0
    patternCounts.set(comp.stylingPattern, count + 1)
  }
  const dominantPattern = [...patternCounts.entries()].sort((a, b) => b[1] - a[1])[0]?.[0]

  if (dominantPattern === 'cva') {
    lines.push('Variant pattern: class-variance-authority (CVA)')
  }
  if (dominantPattern === 'cn' || stack.components === 'shadcn') {
    lines.push(`Utility: \`cn()\` from \`${stack.srcDir}lib/utils.ts\``)
  }
  lines.push('')

  // Rules
  lines.push('## Rules')
  if (stack.components === 'shadcn') {
    lines.push('1. Check existing CVA variants before adding one-off classNames')
    lines.push('2. Use cn() for conditional class logic — never string concatenation')
    lines.push('3. shadcn components accept a className prop — use it for page-level overrides')
    lines.push('4. New variants go in the cva() definition, not inline on usage sites')
  } else {
    lines.push('1. Prefer existing component patterns over creating new abstractions')
    lines.push('2. Use the project\'s established styling pattern consistently')
    lines.push('3. Check if a similar component already exists before creating new ones')
  }
  lines.push('')

  // Component index
  if (stack.componentPatterns.length > 0) {
    lines.push('## Component Index (auto-scanned)')
    lines.push('| Component | Path | Usages | Pattern |')
    lines.push('|-----------|------|--------|---------|')
    for (const comp of stack.componentPatterns.slice(0, 30)) {
      lines.push(`| ${comp.name} | ${comp.filePath} | ${comp.usageCount} | ${comp.stylingPattern} |`)
    }
    lines.push('')
  }

  // CVA variants detail
  const cvaComponents = stack.componentPatterns.filter(c => c.variants && c.variants.length > 0)
  if (cvaComponents.length > 0) {
    lines.push('## CVA Variants')
    for (const comp of cvaComponents) {
      lines.push(`### ${comp.name}`)
      lines.push(`Variants: ${comp.variants!.join(', ')}`)
      lines.push('')
    }
  }

  return lines.join('\n')
}

function generateConventions(stack: DetectedStack): string {
  const lines: string[] = [
    '# Project Conventions',
    '<!-- Auto-generated by vibe-design sync -->',
    '',
    '## Stack',
    `- Framework: ${stack.framework}${stack.frameworkVersion ? ` v${stack.frameworkVersion}` : ''}`,
    `- Router: ${stack.router || 'N/A'}`,
    `- CSS: ${stack.css}${stack.tailwindVersion ? ` v${stack.tailwindVersion}` : ''}`,
    `- Components: ${stack.components}`,
    `- TypeScript: ${stack.typescript ? 'yes' : 'no'}`,
    '',
    '## File Organization',
  ]

  if (stack.components === 'shadcn') {
    lines.push(`- UI primitives: ${stack.componentsDir}ui/ (shadcn)`)
  }
  lines.push(`- Feature components: ${stack.componentsDir}`)
  if (stack.router === 'app') {
    lines.push(`- Page-level: ${stack.appDir}**/page.tsx`)
  } else if (stack.router === 'pages') {
    lines.push(`- Page-level: ${stack.appDir}`)
  }
  lines.push('')

  lines.push('## Styling Pattern')
  if (stack.css === 'tailwind') {
    lines.push('- Primary: Tailwind utility classes')
    if (stack.components === 'shadcn') {
      lines.push(`- Composition: cn() from ${stack.srcDir}lib/utils.ts`)
      lines.push('- Variants: class-variance-authority (CVA)')
    }
    lines.push('- Never: inline styles, CSS modules (unless existing pattern)')
  } else {
    lines.push(`- Primary: ${stack.css}`)
  }
  lines.push('')

  lines.push('## Detected Patterns')
  if (stack.components === 'shadcn') {
    lines.push('- className always uses cn() when conditional')
    lines.push('- Colors reference semantic tokens (text-muted-foreground, not text-gray-500)')
  }
  if (stack.css === 'tailwind') {
    lines.push('- Responsive: mobile-first (base → sm → md → lg)')
    lines.push('- Dark mode: dark: prefix')
  }
  lines.push('')

  return lines.join('\n')
}

function generateVibeConfig(stack: DetectedStack): string {
  const config = {
    port: 2337,
    autoTrigger: true,
    screenshotDefault: false,
    screenshotScale: 2,
    claudeCommand: 'claude',
    excludeComponents: [],
    customSkills: [],
    overlay: {
      activationKey: 'd',
      position: 'bottom-right',
    },
    detection: {
      srcDir: stack.srcDir,
      componentsDir: stack.componentsDir,
      appDir: stack.appDir,
    },
  }
  return JSON.stringify(config, null, 2)
}

function generateClaudeSkill(): string {
  return `# Vibe Design — Claude Code Skill

When you see "design task" or are pointed at DESIGN_TASK.md:

1. Read \`.vibe/tasks/DESIGN_TASK.md\` fully — intent section first
2. If screenshots are present, view them to understand the visual problem
3. Read relevant skills:
   - \`.vibe/skills/TAILWIND.md\` — always read for Tailwind projects
   - \`.vibe/skills/COMPONENTS.md\` — read if component library detected
   - \`.vibe/skills/CONVENTIONS.md\` — always read
4. Open the target file at the specified line
5. Consider the enrichment context and computed styles
6. Make the minimal change that satisfies the design intent
7. Respect all constraints listed in the task
8. If the component is shared (used in multiple files):
   - Check that the change works across all usage locations
   - If change would break other usages, create a variant instead
9. After changes:
   - Update DESIGN_TASK.md status to "done"
   - Add "Changes Made" section describing what changed and why
   - Note any convention violations that were fixed
10. Never change component APIs (props interface) without noting it
11. Prefer project conventions (semantic tokens, CVA patterns) over ad-hoc classes
`
}
